"""Interface de persistência consumida pelos casos de uso narrativos."""

from typing import Any, Protocol
from uuid import UUID


class NarrativeStore(Protocol):
    def create_timeline_event(self, *, story_id: UUID, values: dict[str, Any]) -> Any: ...
    def list_timeline_events(self, story_id: UUID) -> list[Any]: ...
    def create_plot_thread(self, *, story_id: UUID, values: dict[str, Any]) -> Any: ...
    def list_plot_threads(self, story_id: UUID) -> list[Any]: ...
    def create_arc(self, *, story_id: UUID, values: dict[str, Any]) -> Any: ...
    def get_arc(self, arc_id: UUID) -> Any | None: ...
    def list_arcs(self, story_id: UUID) -> list[Any]: ...
    def create_chapter(self, *, story_id: UUID, values: dict[str, Any]) -> Any: ...
    def list_chapters(self, story_id: UUID) -> list[Any]: ...
