"""Interface de persistência consumida pelos casos de uso de personagens."""

from typing import Any, Protocol
from uuid import UUID


class CharacterStore(Protocol):
    def create(self, *, story_id: UUID, values: dict[str, Any]) -> Any: ...
    def list_for_story(self, story_id: UUID) -> list[Any]: ...
    def get_in_story(self, story_id: UUID, character_id: UUID) -> Any | None: ...
    def create_fact(self, *, story_id: UUID, values: dict[str, Any]) -> Any: ...
    def list_facts(self, story_id: UUID) -> list[Any]: ...
    def get_fact_in_story(self, story_id: UUID, fact_id: UUID) -> Any | None: ...
    def create_knowledge(self, *, character_id: UUID, values: dict[str, Any]) -> Any: ...
    def list_knowledge(self, character_id: UUID) -> list[Any]: ...
    def create_relationship(self, *, story_id: UUID, values: dict[str, Any]) -> Any: ...
    def list_relationships(self, story_id: UUID) -> list[Any]: ...
