"""Interface de persistência consumida pelos casos de uso de histórias."""

from typing import Any, Protocol
from uuid import UUID


class StoryStore(Protocol):
    def create(self, *, user_id: UUID, title: str, premise: str) -> Any: ...
    def get(self, story_id: UUID) -> Any | None: ...
    def update(self, story: Any, changes: dict[str, str]) -> Any: ...
    def create_preferences(self, *, story_id: UUID, tone: str) -> Any: ...
    def get_preferences(self, story_id: UUID) -> Any | None: ...
